{{- $fullName := include "liblaravel.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
            path: /
            pathType: Prefix
