apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "liblaravel.fullname" . }}-env
data:
  APP_DEPLOYMENT_ENV: {{ quote .Values.environment }}
  APP_NAME: {{ include "liblaravel.fullname" . }}
  APP_DOMAIN: {{ quote .Values.ingress.host }}
  APP_URL: "http://{{ .Values.ingress.host }}"
  APP_KEY: "base64:fJZN6TrXzqgb6ppUrpV27n49wb3S+o3Q4Odm5zZWosY="
  DB_CONNECTION: "mysql"
  DB_HOST: {{ quote .Values.database.host }}
  DB_DATABASE: {{ quote .Values.database.name }}
  # Use the uri dns - set the user and password to null to the dns is used
  DB_DNS: "uri:file:///vault/secrets/dns"
  DB_USERNAME: "null"
  DB_PASSWORD: "null"